"""empty message

Revision ID: 2aec777abfb2
Revises: 02c1c27aa0bb
Create Date: 2022-05-18 17:37:10.312513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aec777abfb2'
down_revision = '02c1c27aa0bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
