"""empty message

Revision ID: 6f29fc15593b
Revises: 2aec777abfb2
Create Date: 2022-05-18 18:47:35.036511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f29fc15593b'
down_revision = '2aec777abfb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
