"""empty message

Revision ID: 75a5e112cc70
Revises: d87c93d06e00
Create Date: 2022-05-28 20:33:06.671693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a5e112cc70'
down_revision = 'd87c93d06e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    t_purchases = op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_set_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_set_id'], ['item_sets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    connection = op.get_bind()

    connection.execute(
        sa.insert(t_purchases).values([
            {
                'item_set_id': 1,
                'value': 3,
                'date': '2021-01-01',
                'user_id': 1,
                'is_complete': True
            },
        ])
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchases')
    # ### end Alembic commands ###
