"""empty message

Revision ID: aa66e2ac397c
Revises: 0c0a88cb1f49
Create Date: 2022-05-18 20:09:44.343014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa66e2ac397c'
down_revision = '0c0a88cb1f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    t_suppliers = op.create_table(
    'suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=12), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###

    connection = op.get_bind()

    connection.execute(
        sa.insert(t_suppliers).values([
            {
                'name': 'supplierexample',
                'email': 'supplieremail@erpsystem.ru',
                'phone_number': '81234567891',
                'address': 'Москва, Тверская ул, д. 1'
            },
        ])
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suppliers')
    # ### end Alembic commands ###
