"""empty message

Revision ID: c81799eaa469
Revises: c6cc9c440371
Create Date: 2022-05-26 14:43:00.175099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c81799eaa469'
down_revision = 'c6cc9c440371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    t_stores = op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###

    connection = op.get_bind()

    connection.execute(
        sa.insert(t_stores).values([
            {
                'address': 'ул. Пушкина, д. Колотушкина',
                'phone_number': '88005553535',
                'email': 'proshepozvonit@chemukogoto.zanimat'
            },
        ])
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stores')
    # ### end Alembic commands ###
