"""empty message

Revision ID: d87c93d06e00
Revises: c81799eaa469
Create Date: 2022-05-27 19:47:34.240822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd87c93d06e00'
down_revision = 'c81799eaa469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    t_item_sets = op.create_table('item_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('contracts_item_sets',
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('item_set_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['item_set_id'], ['item_sets.id'], )
    )
    # ### end Alembic commands ###

    connection = op.get_bind()

    connection.execute(
        sa.insert(t_item_sets).values([
            {
                'name': 'Печенье на сухую',
            },
        ])
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contracts_item_sets')
    op.drop_table('item_sets')
    # ### end Alembic commands ###
