name: CI

on:
  pull_request:

jobs:
  # This workflow contains a single job called "build"
  check-backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres        
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest coverage 
        working-directory: "./backend/"
      - name: Lint wiht flake8
        run: |
          flake8
        working-directory: "./backend/"
      - name: Test with coverage and pytest
        run: |
          sudo service postgresql start
          make test-ci
        working-directory: "./backend/"
  check-frontend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: npm install, build, and lint
      run: |
        npm ci
        npm run build --if-present
        npm run lint
      env:
        CI: true
      working-directory: "./frontend/"
